---
- hosts: localhost
  become: true
  tasks:
  - name: Install a list of packages
    apt:
      name: "{{ packages }}"
    vars:
      packages:
      - htop
      - vim
      - git
      - curl
      - vagrant
      - virtualbox
      - composer
  - name: Download chrome
    shell: wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
  - name: Install chrome
    shell: sudo dpkg -i google-chrome-stable_current_amd64.deb
